# **Basic XOR ANN using NumPy**

In [1]:
import numpy as np

# Define the sigmoid function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# XOR input and output data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# Initialize weights randomly
np.random.seed(42)
weights_input_hidden = np.random.rand(2, 2)  # 2 input neurons, 2 hidden neurons
weights_hidden_output = np.random.rand(2, 1) # 2 hidden neurons, 1 output neuron

# Set learning rate and number of epochs
learning_rate = 0.1
epochs = 100000

# Training loop
for epoch in range(epochs):
    # Forward propagation
    hidden_input = np.dot(X, weights_input_hidden)
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, weights_hidden_output)
    final_output = sigmoid(final_input)

    # Calculate the error
    error = y - final_output

    # Backward propagation
    d_output = error * sigmoid_derivative(final_output)

    error_hidden_layer = d_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_output)

    # Update weights
    weights_hidden_output += hidden_output.T.dot(d_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate

# Testing the trained network
print("Trained Weights (Input -> Hidden):")
print(weights_input_hidden)
print("Trained Weights (Hidden -> Output):")
print(weights_hidden_output)

print("\nOutput after training:")
print(final_output)

print("\nOutput after training (rounded):")
print(np.round(final_output))


Trained Weights (Input -> Hidden):
[[0.92668235 7.72650589]
 [0.92668541 7.7282175 ]]
Trained Weights (Hidden -> Output):
[[-33.20972541]
 [ 26.41319563]]

Output after training:
[[0.03234997]
 [0.93150506]
 [0.93150511]
 [0.09134328]]

Output after training (rounded):
[[0.]
 [1.]
 [1.]
 [0.]]
